on:
  pull_request:
  push:
jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-22.04
        - ubuntu-24.04
        - windows-2022
        - macos-14
        - macos-13
    steps:
    - uses: actions/checkout@v4
    - uses: sbt/setup-sbt@v1
    - uses: actions/setup-java@v4
      with:
        java-version: 11
        distribution: adopt
    - run: sbt compile run
